Exponential
BoostGSoC19/Real pull request #22
Opened 2019-07-15 00:55 UTC by universenox

2019-07-15 12:17 UTC, sdavtaker requested changes
a.out should not be here.

2019-07-15 12:17 UTC, sdavtaker commented on include/real/const_precision_iterator.hpp
>          /// the default max precision to use if the user hasn't provided one.
Just curiosity, but why 3 slashes? I saw it in other places.

2019-07-15 12:17 UTC, sdavtaker commented on include/real/const_precision_iterator.hpp
> +                unsigned int _precision;
If this precision refers to how many digits, size_t may be more appropriate than unsigned int.

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                    (*this).positive = positive;
Just for consistency I would move this line below the next one.

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                    // std::cout << "dthis: " << this->as_string() << ", res: " << residual.as_string() << '\n';
is the dthis a typo?

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                    while (distance.size() > max_precision + 10)
Please add braces in all loops, it is just a style thing, but we want to keep it consistent.

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                    while ((*this).size() > max_precision + 10)
Why 10? Can you extract it into a constant?

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                        if (positive)
Braces on if/else too please.

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +            // perform (*this)^(exponent)
Please stage the commented code and remove it from this PR

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                        this->digits[index] = 9;
Please refer to 9 as a constant too, so it simplify changes in the future.

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +            /// @TODO allow ctor from any integral type, use this in real_explicit
It will take 2 lines to remove the todo, you just need to add template<typename T>  and an static_assert in the first line checking for "integral_type".

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                if (this->digits == zero || this->digits == empty) {
why you compare against an empty vector in place of just asking .empty() to the vector?

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                    if (other.digits == zero || !other.positive || other.digits == empty)
you can replace this if by " return ! (condition)"

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                std::vector<int> empty = {};
Why not asking .empty() to the vector?

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                    if (other.digits == zero || other.positive || other.digits == empty)
you can replace by 'return ! condition;'

2019-07-15 12:17 UTC, sdavtaker commented on include/real/exact_number.hpp
> +                    return (int)digits.size() <= exponent;
I would replace the (int) by decltype(exponent) or keep and exponent_t around for future changes.

2019-07-15 12:17 UTC, sdavtaker commented on include/real/irrational_helpers.hpp
> +                // we hardcoded 10. There seems to be precision issues, otherwise.
Make 10 a constant please

2019-07-15 12:17 UTC, sdavtaker commented on include/real/irrational_helpers.hpp
> +            // refer to the Chudnovsky formula for Pi.
Please stage this code and make the PR without it.

2019-07-15 12:17 UTC, sdavtaker commented on include/real/real.hpp
> +    return boost::real::real (std::to_string(x));
space

2019-07-15 12:17 UTC, sdavtaker commented on include/real/real_data.hpp
> +                // case OPERATION::POWER: {
Please stage and remove from this PR.

2019-07-15 12:17 UTC, sdavtaker commented on test.cpp
> +#include <real/real.hpp>
Is this file suppose to be here?

2019-07-15 12:17 UTC, sdavtaker commented on test.cpp
> +    c^= b;
Please do not use ^ as power operator, it may be confusing in C++.

2019-07-15 16:23 UTC, universenox commented on include/real/const_precision_iterator.hpp
>          /// the default max precision to use if the user hasn't provided one.
Three slashes means doxygen will pick it up. If autobrief is on then it'll get put as part of the doxygen brief description.

2019-07-15 16:26 UTC, universenox commented on include/real/exact_number.hpp
> +                    // std::cout << "dthis: " << this->as_string() << ", res: " << residual.as_string() << '\n';
The cout statement was for debugging. I tend to put a lot of them throughout the code when I'm trying to see how a value changes at each step, etc. I used dthis to tell myself that the output was the value from division. I'll remove it.

2019-07-15 16:27 UTC, universenox commented on include/real/exact_number.hpp
> +                std::vector<int> empty = {};
Oh, didn't know there was this functionality. I'll replace it.

2019-07-15 16:38 UTC, universenox commented on include/real/exact_number.hpp
> +                    while ((*this).size() > max_precision + 10)
Truncating too much in the intermediary steps previously caused problems in converging. 10 was arbitrary. It just worked for the test cases I had. I'll test this, and create a constant for it if it is still needed for the current division algorithm.

2019-07-15 18:43 UTC, universenox commented
Okay, I have updated it with your suggestions.

2019-07-23 03:11 UTC, sdavtaker approved these changes

2019-07-23 21:52 UTC, Laouen requested changes
Fix conflicts and this PR is ready to merge!

2019-07-25 04:23 UTC, universenox commented
This should be good to go now

2019-07-25 13:01 UTC, sdavtaker reviewed
Added a few more comments.

2019-07-25 13:01 UTC, sdavtaker commented on include/real/irrational_helpers.hpp
> +#include<math.h>
Space consistency

2019-07-25 13:01 UTC, sdavtaker commented on bench/include/benchmark_helpers.hpp
> +    case boost::real::OPERATION::ADDITION:
This cases are at the same indentation level of the switch, but those below are one level inside. Please keep them consistent.

2019-07-25 13:01 UTC, sdavtaker commented on bench/include/benchmark_helpers.hpp
> +    }
Please add a default case with an exception.

2019-07-25 13:01 UTC, sdavtaker commented on bench/include/benchmark_helpers.hpp
> +        case (Comparison::greater_than):
operations are defined all uppercase above, but comparizons are defined with camelcase for the comparison class and all lower_case for the kind name, can you keep them all the same? UPPER_CASE seems to be the right one. 
No need to solve this now, but if you don't solve please create a note somewhere so we don't forget.

2019-07-25 13:01 UTC, sdavtaker commented on bench/include/benchmark_helpers.hpp
> +    }
Please add a default case with an exception.

2019-07-25 13:01 UTC, sdavtaker commented on bench/real_construction_bench.cpp
> +        for (int i = 0; i < state.range(0); i++)
Please add braces

2019-07-25 13:01 UTC, sdavtaker commented on bench/real_op_evaluation_bench.cpp
> +    boost::real::real b ("34");
Indentation in the for.

2019-07-25 13:01 UTC, sdavtaker commented on bench/real_op_evaluation_bench.cpp
> +    a.get_real_itr().cend(); // force evaluation
Indentation

2019-07-25 13:01 UTC, sdavtaker commented on include/real/real_exception.hpp
> +
empty line

2019-07-25 17:43 UTC, universenox commented
Okay, I incorporated your suggestions.

2019-07-25 18:14 UTC, sdavtaker approved these changes

2019-07-27 03:08 UTC, merged